services:
  nodex:
    image: pajeritmia/nodex:latest
    container_name: nodex-app
    restart: unless-stopped
    ports:
      - "3050:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - nodex_data:/app/data

volumes:
  nodex_data:
